package ba.unsa.etf.rpr;

public enum Grad {
    SARAJEVO, TUZLA, ZENICA, TRAVNIK, ODZAK, LIVNO, MOSTAR, BIHAC, GORAZDE, SIROKI_BRIJEG, BRCKO,
    MRKONJIC_GRAD, BANJA_LUKA, PRIJEDOR, DOBOJ, SAMAC, BIJELJINA, ZVORNIK, PALE, FOCA, TREBINJE;
}
